spring.application.name=movie_booking
# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/moviebooking
spring.datasource.username=root
spring.datasource.password=Root12345!

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=moviebooking-secret-key-this-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packagesToScan=com.moviebooking.controller

# App Port
server.port=8080